### PR TITLE
test

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by hrishin** [comment]
@rawlingsj so wouldn't it be nice to delete/archive PR deployments e.g.http://google-demo.jx-cb-kubecd-google-demo-pr-2.35.205.83.67.nip.io/?

**Comment by rawlingsj** [comment]
@hrishin yeah, there's a kubernetes cron job that tears down merged or closed preview environments so this will be cleaned up shortly.  Ideally we'll switch this to be event based using prow on merge to master rather than a cron job.

**Comment by hrishin** [comment]
thanks :+1: for the update.

**Comment by rawlingsj** [comment]
> thanks 👍 for the update.

@hrishin np - glad you're interested :)

**Comment by hrishin** [comment]
Yes :)

**Pull request merged**
